### ISSUE TITLE
Export "decorate" to make it easy to create custom monads

### ISSUE THREAD

**Issue by pbadenski** [monet/monet.js#108]
Monet.js can serve not only as a great functional library, but ease in the pain by providing a template to create your own monads.

**Comment by ulfryk** [comment]
@pbadenski - we can expose `decorate` but it will probably be gone at some point - we're considering rewrite of source to TS in next major release to avoid certain amount of internal issues… So I'm not sure if this is a good idea as it'll be a breaking change then…

**Comment by pbadenski** [comment]
Awesome, thanks! Waiting for the next release then! I'll fork monet.js and use the fork until then.

**Comment by char0n** [comment]
@ulfryk maybe just follow-up question regarding the typescript rewrite and applicatives. I found this [question](https://github.com/fantasyland/fantasy-land/issues/50) regarding applicates. In monet we have Scalaz approach to `ap`, yet fantasy land spec for `ap` is different. Will monet.js conform to fantasy-land spec in next major release ?

**Comment by ulfryk** [comment]
@char0n I can't answer your question now as decision was not made yet… ;)

**Comment by char0n** [comment]
@ulfryk I think the decision doesn't have to be made anymore. The fantasyland 1.x.y spec adopted monets approach to applicatives. Sometimes patience pays off ;] I have created #112 for monet to be compatible with next release of ramda. More info there.
