### ISSUE TITLE
Incorrect IO monad example

### ISSUE THREAD

**Issue by char0n** [monet/monet.js#110]
I don't think IO monad example on read function is correct.

```javascript
var read = IO(function (id) { return $(id).text() })
```

I think it should be 

```javascript
var read = function(id) {
  return IO(function() {
    return $(id).text();
  });
}
```

Or ES2017 version
```javascript
const read = id => IO(() => $(id).text());
```

**Update**:

I thinks the whole IO example doesn't make sense and is not even executable code. IO monad is all about effects but instead of effects the example deals with IO object instances. I think the correct code should look like this.

```javascript
const { Monet: { curry }, IO } = require('monet');

// simulating jQuery
const $ = function() {
  return {
    text() {
      return 'text';
    },
  };
}

var read = function(id) {
  return IO(function() {
    return $(id).text();
  });
};

var write = curry(function(id, value) {
  return IO(function() {
    return $(id).text(value);
  });
});

var toUpper = function (text) { return text.toUpperCase() }
var changeToUpperIO = read("#myId").map(toUpper).flatMap(write("#myId"));

changeToUpperIO.run();
```

**Comment by char0n** [comment]
Maybe just to clarify. I will update the /docs on develop, but what we need to do is to update gh-pages branch ASAP to provide working example of IO monad.

PS: what is the relation between gh-pages and dev/docs ?

Thanks for claryfing

**Comment by ulfryk** [comment]
There is no straight relation - best way to update would be to just add another PR against `gh-pages` branch…

**Comment by char0n** [comment]
@ulfryk PR provided

**Comment by char0n** [comment]
@ulfryk can we reopen this ? https://github.com/monet/monet.js/blob/develop/docs/IO.md seems to contains invalid examples

**Comment by ulfryk** [comment]
@char0n - working on it
