### ISSUE TITLE
Add 'isInstance' method to monad statics 

### ISSUE THREAD

**Issue by ulfryk** [monet/monet.js#111]
This should help with situations like one described in #109.

API proposal:

```typescript
const some = Some(1);
const one = 1;

Maybe.isInstance(some);
// => true

Maybe.isInstance(one);
// => false
```

**Comment by char0n** [comment]
Maybe.isInstance sounds good. In following lines I would try to collaborate on more flexible solution. I dealt with the same problem while prototyping fantasy land spec implementation to learn it's laws. I will demonstrate on reference implementation of Identity monad from [ramda-adjunct](https://github.com/char0n/ramda-adjunct).

I suggest for a property called `@@type` on [constructor](https://github.com/char0n/ramda-adjunct/blob/master/src/internal/fantasy-land/Identity.js#L12) of every type (Monad, Either, etc..). If not possible, put the `@@type' property on instance of every type.

When we have `@@type` property we can implement type checking [utils](https://github.com/char0n/ramda-adjunct/blob/master/src/internal/fantasy-land/util.js#L14) according to fantasy-land spec. Then for example for implementing Setoid spec of fantasy-land ([equals method](https://github.com/char0n/ramda-adjunct/blob/master/src/internal/fantasy-land/traits.js#L19)) we must obey the following laws:

```javascript
a.equals(b) === true when:
```
 1. `a` and `b` must be the same Setoid 
 2. their wrapped values must equal as well

Currently Setoid spec in monet for Maybe is implemented by checking if `b` has `isNone` function. I think better solution would be to introduce ```@@type``` property with value `monet/Maybe`. Then we can implement Maybe.isInstance as

```javascript
Maybe.prototype.isInstance = function(other) {
   const otherType = other['@@type'] || other.costructor['@@type'];
   return otherType.endsWith('Maybe');
}
```
With `@@type` interface I see the following benefits:
 - making Setoid and other spec fantasy-land compatible out-of the box
 - using convention already used by ramda-fantasy, ramda-adjunct and some other libraries
 - `@@type` makes same algrebraic types interoperable between various libraries making following possible
```javascript
import { IdentityRA } from 'ramda-adjunct';
import { Identity as IdentityM } from 'monet';

IdentityRA.of(1).equals(IdentityM.of(1)) === true
``` 

I hope this make some sense.

**Comment by ulfryk** [comment]
Sounds good. Can you just elaborate on why `.endsWith('Maybe')`? Why not `otherType === 'Maybe'` ?

**Comment by char0n** [comment]
If I remember correctly what I had in mind, to enable namespacing the types.

**Comment by ulfryk** [comment]
done in #150
