### ISSUE TITLE
Identity doesn't implement Apply spec

### ISSUE THREAD

**Issue by char0n** [monet/monet.js#115]
Is there a reason why Identity doesn't implement Apply spec ? If no, I will provide a pull request to compensate. Without Apply spec on Identity it is not possible to use lifting on this monadic type.

**Comment by ulfryk** [comment]
There isn't any actually. Identity seems just to be ignored and not included in docs… PR is welcome :)

**Comment by char0n** [comment]
Will do.  Is there a way for me to modify the docs ?

**Comment by ulfryk** [comment]
It depends.. What would you like to change/add ?

**Comment by char0n** [comment]
Just to include Identity into docs. My team members did not know there is such a type, I had to point them to source code.

**Comment by char0n** [comment]
And also I could correct the #110

**Comment by ulfryk** [comment]
:+1: (for identity please add new file in [docs/](https://github.com/cwmyers/monet.js/tree/develop/docs) directory - same as already is done with Maybe and List)

**Comment by char0n** [comment]
Overlooked it on master branch. Wouldn't it be more practical to set develop as default branch ?

- pull request will be automatically sent against this branch
- more activity on develop then on master

**Comment by ulfryk** [comment]
Would be :)

@cwmyers - can you help us here a little and `set develop as default branch` ?
