### ISSUE TITLE
Who owns https://github.com/monet and https://github.com/monetjs ?

### ISSUE THREAD

**Issue by cwmyers** [monet/monet.js#129]
I would like to move monet.js to a new github org so we can split up the project a little better.

I've noticed that https://github.com/monet and https://github.com/monetjs seem to be taken already.  Has anyone on this project done this?

Cheers,
Chris

**Comment by vegansk** [comment]
@cwmyers, you can write to support@github.com, and if these organizations are inactive, they can transfer these names to you, as they did it for me with https://github.com/eldis :-)

See https://help.github.com/articles/name-squatting-policy

**Comment by ulfryk** [comment]
@cwmyers I've taken them over some time ago so we can use them for monet ;)

**Comment by cwmyers** [comment]
Thanks so much @ulfryk 

So how do we decide which one to go with?

**Comment by cwmyers** [comment]
I'm leaning towards simply 'monet'

What do you all think?

**Comment by ulfryk** [comment]
:+1: for simply `monet` ;)

I've reserved the other on just in case.

**Comment by cwmyers** [comment]
The repo has now been moved to monet! \o/

**Comment by cwmyers** [comment]
I'll sent up a redirect from the old ghpages

**Comment by cwmyers** [comment]
So redirects are working for cwmyers/monet.js -> monet/monet.js but hits to cwmyers.github.io/monet.js are 404ing.

This is annoying.  I wonder if I need to create a new monet.js under my account to redirect to monet/monet.js but I'm worried that will break other links

**Comment by ulfryk** [comment]
@cwmyers looks like ne site is on https://monet.github.io/monet.js/ (a link in docs has `.com`)

**Comment by char0n** [comment]
https://cwmyers.github.io/monet.js/ is still returning 404. Unfortunately this link has been used for years and it is all over the internet. Is it possible to at least re-init the original repo with gh-pages branch and put `index.html` with the following code there ?

```html
<!DOCTYPE HTML>
<html lang="en-US">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="refresh" content="1; url=https://monet.github.io/monet.js/">
        <script type="text/javascript">
            window.location.href = "https://monet.github.io/monet.js/"
        </script>
        <title>Page Redirection</title>
    </head>
    <body>
        <!-- Note: don't tell people to `click` the link, just tell them that it is a link. -->
        If you are not redirected automatically, follow this <a href='https://monet.github.io/monet.js/'>link to new monet site</a>.
    </body>
</html>
```

**Comment by cwmyers** [comment]
I think if I do that then older versions published to node and bower may
break as the redirects will stop. I'll look into it.

**Comment by cwmyers** [comment]
Ok, I've recreated the old repo and put in the redirects.  Bower installs continue to work.

I'll close this issue 😃
