### ISSUE TITLE
Maybe.fromUndefined

### ISSUE THREAD

**Issue by jh3141** [monet/monet.js#132]
When accessing values in objects that may or may not be defined, it would be useful to be able to directly convert this to a `Maybe`, e.g.:

```
let myHash = { "something": "a value", "somethingElse": "another value" };
let myKey = prompt ("Choose either 'something' or 'somethingElse'");
let myValue = Maybe.fromUndefined(myHash[myKey]);
```

I note that with the current development version you can do this using `fromFalsy`, but obviously this would fail if `false`, `0`, or any other "falsy" values are expected to be produced, so a variant that directly tests against `undefined` would be handy.

**Comment by ulfryk** [comment]
You can use `Maybe.fromNull` for this purpose (name may be misleading but it'll turn `null` or `undefined` into `None` and any other value into `Some(value)`)

**Comment by jh3141** [comment]
True, but there's still a potential problem if there are null values hanging around that you want to treat as distinct from undefined (e.g. if using the distinction "null" => exists but value isn't known, "undefined" => doesn't exist).

**Comment by ulfryk** [comment]
As you can find in docs:
> **It's important to note that monet `Maybe` implementation threats `null` and `undefined` values in special way. Any attempt to provide `null` or `undefined` to constructor (other than `fromNull` or `fromFalsy`) will cause exception. Same will happen if it's mapped to `null` or `undefined`.**

But I'll probably add `fromUndefined` - just you have to be aware that `.fromUndefined(null)` will throw.

**Comment by ulfryk** [comment]
done with #150
