### ISSUE TITLE
Installation using npm using a git URL gives a broken install

### ISSUE THREAD

**Issue by jh3141** [monet/monet.js#143]
Reloading all the dependencies for a project previously using v0.9.0-alpha.2, I found that npm had pulled in v0.9.0-alpha.4, which is apparently empty of actual code:

```
Andys-Mac-mini:tackta andy$ ls -l node_modules/monet
total 56
-rw-r--r--  1 andy  staff  2708 21 Jun 21:53 CHANGELOG.md
-rw-r--r--  1 andy  staff  1078 21 Jun 21:53 LICENSE
-rw-r--r--  1 andy  staff  5175 21 Jun 21:53 README.md
-rw-r--r--  1 andy  staff  9928 21 Jun 21:54 package.json
Andys-Mac-mini:tackta andy$ grep '\"version\":' node_modules/monet/package.json  
  "version": "0.9.0-alpha.4"
```
I'd previously installed from a git URL in order to get the development version.  But it seems that doing so relied on the presence of the "dist" directory, which was removed from the repository in commit 5df188ed767b038b595925f35f4a5ff38ed8e2e0 -- is installation directly from github unsupported?

**Comment by ulfryk** [comment]
> is installation directly from github unsupported

`dist` was available in repo only temporary for debugging purposes. It's onlu published to NPM

using `"monet": "0.9.0-alpha.4"` in `"dependencies"` section of your package json should work fine
