### ISSUE TITLE
areEqual() and equals()() functions

### ISSUE THREAD

**Issue by jh3141** [monet/monet.js#146]
Looking at the code, there are two functions defined for equality testing, `areEqual` and `equals`, which could both be uesful generally, but aren't currently exported.  Perhaps they should be included in the `Monet` object with most of the other free functions?

**Comment by ulfryk** [comment]
These are internal implementation functions which can/would change. All Monet types extend Setoid, so you can `a.equals(b)` (and that is public, stable API).
