### ISSUE TITLE
Maybe.Just declaration is wrong in documentation

### ISSUE THREAD

**Issue by tryshchenko** [monet/monet.js#156]
> var maybeAddress = Maybe.just('Dulwich, London')
> var maybeSurname = Maybe.just('Baker')
> var maybeForename = Maybe.just('Tom')

Maybe.just should be Maybe.Just
Fixed in https://github.com/monet/monet.js/pull/155
 
I was confused, do I need to prepare PR to develop-pages or gh-pages. I created a PR to gh-pages as it looks more actual, however feel free to make it to develop-pages if it's required

**Comment by ulfryk** [comment]
Fixed with #155
