### ISSUE TITLE
Trouble having monet function with webpack

### ISSUE THREAD

**Issue by binyata** [monet/monet.js#158]
My current repo includes the monet module. I am experimenting at this point, but would like to see how switching from jspm to webpack would improve the overall UI experience. 

The trouble at hand is that monet is having trouble being defined, more specifically a property within monet. 

Unhandled rejection TypeError: Cannot set property 'Monet' of undefined

This is the syntax I see failing:

(function (root, factory) {
    if (( false ? 'undefined' : _typeof(exports)) === 'object') {
        module.exports = factory(root);
    } else if (true) {
        !(__WEBPACK_AMD_DEFINE_FACTORY__ = (factory),
				__WEBPACK_AMD_DEFINE_RESULT__ = (typeof __WEBPACK_AMD_DEFINE_FACTORY__ === 'function' ?
				(__WEBPACK_AMD_DEFINE_FACTORY__.call(exports, __webpack_require__, exports, module)) :
				__WEBPACK_AMD_DEFINE_FACTORY__),
				__WEBPACK_AMD_DEFINE_RESULT__ !== undefined && (module.exports = __WEBPACK_AMD_DEFINE_RESULT__));
    } else {
        root.curry = factory(root);
    }
})(undefined, function (root) {
    "use strict";

    var curry = function curry(fn, args) {
        return function () {
            var args1 = args.append(List.fromArray(Array.prototype.slice.call(arguments)));
            return args1.size() >= fn.length ? fn.apply(this, args1.toArray().slice(0, args1.size())) : curry(fn, args1);
        };
    };

    var isFunction = function isFunction(f) {
        return !!(f && f.constructor && f.call && f.apply);
    };

    var idFunction = function idFunction(value) {
        return value;
    };
    var trueFunction = function trueFunction() {
        return true;
    };
    var falseFunction = function falseFunction() {
        return false;
    };

    **var Monet = root.Monet = {};**

    var swap = Monet.swap = function (f) {
        return function (a, b) {
            return f(b, a);
        };
    };

 root.Monet appears to not have Monet defined as a property. I was wondering if there was a way to approach this? I would like to continue using monet, but also be able to change my package manager.

**Comment by ulfryk** [comment]
Hi @binyata :)

Which version of `monet` are you using?

This is how the original code looks like:

```javascript
(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        define(factory)
    } else if (typeof module === 'object' && module.exports) {
        module.exports = factory()
    } else {
        root.notUseMonetGlobalObject = !root.useMonetGlobalObject
        root.Monet = factory(root)
    }
}(this, function (rootGlobalObject) {
```

`root` is defined here.

Your output says that `undefined` is assigned to root instead of `this`. It's probably an issue with webpack (or one of it's loaders) configuration.

**Comment by binyata** [comment]
I am using version ^0.8.10 of monet according to package.json

**Comment by binyata** [comment]
This looks to resolve the problem:

https://stackoverflow.com/questions/34973442/how-to-stop-babel-from-transpiling-this-to-undefined


"
When using Babel 6 and babel-preset-es2015 (or Babel 5), Babel by default assumes that files it processes are ES6 modules. The thing that is causing you trouble is that in an ES6 module, this is undefined, whereas in the "script" case, this varies depending on the environment, like window in a browser script or exports in CommonJS code.

If you are using Babel, the easiest option is to write your code without the UMD wrapper, and then bundle your file using something like Browserify to automatically add the UMD wrapper for you. Babel also provides a babel-plugin-transform-es2015-modules-umd. Both are geared toward simplicity, so if you want a customized UMD approach, they may not be for you.

Alternatively, you would need to explicitly list all of the Babel plugins in babel-preset-es2015, making sure to exclude the module-processing babel-plugin-transform-es2015-modules-commonjs plugin. Note, this will also stop the automatic addition of use strict since that is part of the ES6 spec too, you may want to add back babel-plugin-transform-strict-mode to keep your code strict automatically.
"

Thank you for your responsiveness. I can close this.

**Comment by ulfryk** [comment]
I'd strongly suggest using `0.9.0-alpha.4` - it's an `alpha` because not all features meant for `0.9.0` are there, but it has most `0.8` bugs fixed.
