### ISSUE TITLE
Missing methods

### ISSUE THREAD

**Issue by carlesba** [monet/monet.js#163]
I'm missing some methods according to documentation:

- [ ] `List[].find`
- [ ] `Either[].fold` (`cata` works though)

**Comment by ulfryk** [comment]
@carlesba - which version of monet?

**Comment by carlesba** [comment]
@ulfryk `0.8.10`

**Comment by carlesba** [comment]
You can try `List([1,2,3]).find(x => x < 2)` in browser's console in https://monet.github.io/monet.js/ to replicate

**Comment by ulfryk** [comment]
@carlesba this are known and fixed issues… But still not released. Version `0.9` is under development.

Not enough hands on board to make it faster.

I can suggest using `0.9.0-alpha.4` and guarantee that it's stable (just API is still extending).
And `0.9.0-alpha.4` has all `0.8.10` bugs fixed.
