### ISSUE TITLE
Will there be a v0.9.0 publish

### ISSUE THREAD

**Issue by mingchuno** [monet/monet.js#168]
There is quite some time since the last publish. will there be a version 0.9.0? @ulfryk @cwmyers

**Comment by iainreid820** [comment]
I'm wishfully waiting for this too! Futures support is also something that I saw mentioned in #29 and #102, and a feature that I'm really keen for!

Any news?

**Comment by ulfryk** [comment]
actually `Futures` will not land in `0.9.0` :( 

We strongly suggest usage of https://github.com/fluture-js/Fluture

**Comment by ulfryk** [comment]
`0.9.0` release is close ;)

**Comment by ulfryk** [comment]
as soon #171 is merged (it will close #78) and #154 is fixed.

**Comment by ulfryk** [comment]
Release `0.9.0` is close, please track info in #69
