### ISSUE TITLE
Error: Provide polyfill or use up to date browser/node version to use "Iterable" protocol

### ISSUE THREAD

**Issue by aslack19** [monet/monet.js#186]
I'm seeing this error:
```
Error: Provide polyfill or use up to date browser/node version to use "Iterable" protocol.
    at makeIterable (<...redacted..>/node_modules/monet/dist/monet.js:1211:31)
```
Using:
```
"monet": "^0.9.0-rc.1"
```
```
node --version
v8.9.4
```
Beyond install the monet dependency, is there anything else I need?

thanks.

**Comment by ulfryk** [comment]
I'm not happy to say that but `0.9.0-rc.0` and `0.9.0-rc.1` are broken. Please use `0.9.0-alpha.4` for now…

**Comment by aslack19** [comment]
alas, seeing the same error with `0.9.0-alpha.4` too

**Comment by ulfryk** [comment]
https://github.com/monet/monet.js/blob/0.9.0-alpha.4/src/monet.js

This error was added after `alpha.4` so probably npm on yarn failed to properly reinstall dependency.

**Comment by aslack19** [comment]
Ah yes, my mistake.  Unfortunately that version doesn't have the `orLazy` support.

**Comment by ulfryk** [comment]
That's true, but you can use `.cata(getSomeValueLazily, identity)` for now.

In meantime I'm trying to find enough time to make `0.9.0` stable available as soon as possible…
