### ISSUE TITLE
Reader.bind doesn't seem to chain context properly?

### ISSUE THREAD

**Issue by christav** [monet/monet.js#192]
In experimenting with the reader monad I think I either misunderstand something or the bind implementation doesn't do the right thing when binding multiple readers together. Could somebody point me to where I'm going wrong?

I have the following test code:
```javascript
const { Reader } = require('monet')
const { inspect } = require('util')

const fa = ctx => {
    console.log(`Inside a: ${inspect(ctx)}`)
    return {...ctx, a: ctx.a + 2}
}

const a = () => Reader(fa)

const fb = ctx => {
    console.log(`Inside b: ${inspect(ctx)}`)
    return {...ctx, a: ctx.a * 3}
}

const b = () => Reader(fb)

const fc = ctx => {
    console.log(`Inside c: ${inspect(ctx)}`)
    return { ...ctx, a: ctx.a / 2 }
}

const c = () => Reader(fc)
```

The goal of course being to calculate a new value and chain some context between them.
When I combine these using map, I get:

```javascript
const mapped = a().map(fb).map(fc).run({a: 1})
console.log(`Result of running map: ${inspect(mapped)}`)

Inside a: { a: 1 }
Inside b: { a: 3 }
Inside c: { a: 9 }
Result of running map: { a: 4.5 }
```

Which is exactly what I'd expect - each function does a transformation on the context and passes it through to the next Reader.

However, when I try to use bind with the reader returning functions, I get something very different:
```javascript
const bound = a().bind(b).bind(c).run({a: 1})
console.log(`Result of running chain: ${inspect(bound)}`)

Inside a: { a: 1 }
Inside b: { a: 1 }
Inside c: { a: 1 }
Result of running chain: { a: 0.5 }
```

Instead of passing the updated context through to the next reader, it's resending the original context to each one, with the result that only the last one does anything. I expected that the results of these two calls should be identical.

Is my expectation incorrect?

If not, I think I see the issue in the definition of the bind method on the Reader monad, which is currently:
```javascript
        bind: function (fn) {
            var self = this
            return Reader(function (config) {
                return fn(self.run(config)).run(config)
            })
        }
```

Not that it's using self.run(config) to get the new value to pass to the new reader, but then reruns it with the original context instead of the transformed one via the first reader. I've tried several gyrations to attempt to get the values chaining between the readers with no luck.

Should the code actually look something like this?

```javascript
        bind: function (fn) {
            var self = this
            return Reader(function (config) {
                var xformed = self.run(config)
                return fn(xformed).run(xformed)
            })
        }
```

Again, I'm not sure if I'm just holding it wrong, but the inconsistency between `map` and `bind` seems odd to me, and I'd love assistance in figuring it out.

**Comment by christav** [comment]
Never mind, figured out the issue, PEBKAC. :-)

**Comment by ulfryk** [comment]
@christav - please share what you figured out in case someone else falls in same trap ;)

**Comment by christav** [comment]
Ok, if you insist. 😃

When you use the `map` method, when you run the composition of readers it would run the first reader's function, passing in the config. Then the mapped function would be executed passing in that config as the input to the function, on down the line until the final result was available.

However, when using `bind` it doesn't pass the config from function to function this way. Instead, the result of the previous reader's function is passed in an argument to the outer function, and the original, unchanged config is received via the reader.

To get my example above working, it needed to be rewritten as follows:

```javascript
const { Reader } = require('monet')
const { inspect } = require('util')

const a = val => Reader(ctx => {
    console.log(`Inside a: val = ${val}, ctx = ${inspect(ctx)}`)
    return (val || ctx.a) + 2
})

const b = val => Reader(ctx => {
    console.log(`Inside b: val = ${val}, ctx = ${inspect(ctx)}`)
    return val * 3
})

const c = val => Reader(ctx => {
    console.log(`Inside c: val = ${inspect(val), ctx = ${inspect(ctx)}`)
    return val / 2
})

const bound = a().bind(b).bind(c)

console.log(`Final result = ${bound.run({a: 3})`)
```
When using `bind` the value to calculate on is passed through the "val" parameter, not the context.

To be honest, I find this more useful than the `map` case. This way the context pieces (things like loggers or database access clients, for example) are passed through undisturbed by the actual processing happening.

I will say this behavior was NOT obvious from looking at the type signature or the documentation. I had to read the actual code to figure it out.
