### ISSUE TITLE
`Either.fromPromise`

### ISSUE THREAD

**Issue by wookieb** [monet/monet.js#222]
I found that monet.js does not support async functions very well. How about adding 
`Either.fromPromise`? I can handle that...

**Comment by ulfryk** [comment]
@wookieb - great - I'll wait with `0.9.1` for this feature then :)

**Comment by ulfryk** [comment]
Just maybe add also `.toPromise()` to Either instances ;)

**Comment by wookieb** [comment]
Not sure about how it should work. Return rejected promise for `Left`?

**Comment by ulfryk** [comment]
@wookieb Promise if rejected holds an Error or any other Failure value, so it should be on the left.

```typescript
Left(xyz) --> Promise.reject(xyz)
Right(xyz) --> Promise.resolve(xyz)
```

**Comment by ulfryk** [comment]
`.cata(Promise.reject, Promise.resolve)` ? :D

**Comment by wookieb** [comment]
Ok. Just few minutes
