### ISSUE TITLE
0.9 release

### ISSUE THREAD

**Issue by rickmed** [monet/monet.js#69]
There are a few features in that milestone that I'd love to have. Releasing any time soon? :)

**Comment by ulfryk** [comment]
Hmm.. I didn't have too much time lately, but I'll be back on tacks soon. Maybe you can help a bit ?

**Comment by desfero** [comment]
Hello, if you need some help please let me know. Currently i'm waiting for `Maybe.fromFalsy` and improved throwing of errors

**Comment by ulfryk** [comment]
@desfero I'd like to update docs at least before releasing next `alpha` (actually alphas here seem to be stable - they just introduce new features). See: https://github.com/cwmyers/monet.js/pull/101

If you like to help you can take e.g. `NEL` and move it to new docs style (where at least all methods are listed).

**Comment by jbpros** [comment]
Can we get a release please? 🙏🏻

**Comment by ulfryk** [comment]
I'll have some spare time to finish pending tasks on beginning of next weeks… I promise to provide next alpha before end of next week.

**Comment by jbpros** [comment]
Awesome, thank you! ❤️

**Comment by ulfryk** [comment]
@rickmed @desfero @jbpros - `0.9.0-alpha.4` released - few more upgrades left and we'll be able to use `0.9.0`.

**Comment by jbpros** [comment]
nice one, thanks a lot @ulfryk!

**Comment by ulfryk** [comment]
Now each merge to `develop` branch is published as `nightly` version, can be installed via `npm install monet@nightly`

**Comment by ulfryk** [comment]
RC release is coming #176 :)

**Comment by ulfryk** [comment]
`monet@0.9.0-rc.0` on the wild - some more testing and `0.9.0` will be available next week :tada:

**Comment by gautaz** [comment]
Hi @ulfryk, I just tried `monet@0.9.0-rc.0` under Node.js (I wanted to try using `Reader` with [Sanctuary](https://sanctuary.js.org/) for a back-end project).

Currently requiring `monet` fails with a `TypeError: Cannot read property 'Symbol' of undefined` on `if (!rootGlobalObject.Symbol) {`.

While looking at the [source code](https://github.com/monet/monet.js/blob/v0.9.0-rc.0/src/monet.js#L17), it seems the `factory` function is called with no argument in Node.js case, hence `rootGlobalObject` is `undefined`.

**Comment by ulfryk** [comment]
@gautaz , thanks to @jfspencer this should be fixed now ( #180 ). I'll release `rc.1` ASAP

**Comment by ulfryk** [comment]
`A new version of the package monet (0.9.0-rc.1) was published at 2018-09-18T08:02:07.784Z`

:tada:

If it's ok I'll release `0.9.0` as soon as I can…

**Comment by ulfryk** [comment]
I believe now everything is fixed and should work fine:

`A new version of the package monet (0.9.0-rc.2) was published at 2018-11-18T12:07:29.268Z`

If no new issues arise I'll publish `0.9.0` in the middle of next week.

**Comment by ulfryk** [comment]
@gautaz , @jbpros , @desfero , @rickmed - can you guys confirm that `0.9.0-rc.2` works fine?

**Comment by gautaz** [comment]
@ulfryk Issue fixed for my test case :thumbsup:.
Thanks a lot !

**Comment by ulfryk** [comment]
#202 -> **`A new version of the package monet (0.9.0) was published at 2018-11-20T07:46:25.646Z`**
