### ISSUE TITLE
Equivalents of the Haskell functions `maybe` and `either`

### ISSUE THREAD

**Issue by jh3141** [monet/monet.js#75]
Would be useful to have functions like the Haskell functions `maybe :: b -> (a -> b) -> Maybe a -> b` and `either :: (a -> c) -> (b -> c) -> Either a b -> c` (both of which are documented at http://hackage.haskell.org/package/base-4.9.0.0/docs/Prelude.html).

There are a number of equivalent possible ways of implementing the former function using existing functions; perhaps:

Maybe.maybe = (ifNone, mapIfSome, m) => m.map(mapIfSome).orElse(Maybe.Some(ifNone)).some()

The latter is simply a useful alias that might be more memorable to anyone with Haskell experience than `cata`.  I'm perhaps not quite good enough at category theory, but I think `maybe` is also a catamorphism, so perhaps that should also have a name of `cata` too.

**Comment by jh3141** [comment]
Although I've just noticed in the source that there *is* an implementation of `cata` in Maybe, it just isn't mentioned in the documentation.  So consider this just as a request for aliases and documentation. :)

**Comment by ulfryk** [comment]
@jh3141 - you can use `.fold(ifNone)(mapIfSome)`
